version: '3'

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: 5740305400:AAFrJczOygRrm4208qABXXe5UuLRFoaUSxI
      MONGODB_DATABASE: flying-bot
      MONGODB_USERNAME: flying-bot-admin
      MONGODB_PASSWORD: 5JwDoU44n0H5fgG1YUC
      MONGODB_HOST: mongodb
    volumes:
      - botdata:/app/telegram_bot
    depends_on:
      - mongodb
    networks:
      - botnetwork
      - dbnetwork

  mongodb:
    image: mongo:4.2.23
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: flying-bot-admin
      MONGO_INITDB_ROOT_PASSWORD: 5JwDoU44n0H5fgG1YUC
      MONGO_INITDB_DATABASE: flying-bot
      MONGODB_DATA_DIR: /app/mongodb
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/app/mongodb
    networks:
      - dbnetwork
        
networks:
  botnetwork:
    driver: bridge
  dbnetwork:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  botdata:
    driver: local
